# Generated by Django 4.2.15 on 2024-08-28 02:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_pointsinstance_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapEvents',
            new_name='MapEvent',
        ),
        migrations.RenameModel(
            old_name='MapEventImages',
            new_name='MapEventImage',
        ),
    ]
