# Generated by Django 4.2.15 on 2024-08-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_mapevents_mapevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abr',
            field=models.CharField(default='SJC', help_text='Enter 3 characters as project abbreviation', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
