# Generated by Django 4.2.15 on 2024-08-28 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_project_abr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(help_text='Email address for newsletter signup', max_length=100, unique=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='mapevent',
            name='location',
        ),
        migrations.AddField(
            model_name='mapevent',
            name='loc_x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapevent',
            name='loc_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointsinstance',
            name='loc_x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointsinstance',
            name='loc_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
