# Generated by Django 4.2.15 on 2024-08-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_subscribedusers_remove_mapevent_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribedUsers',
            new_name='SubscribedUser',
        ),
    ]
