# Generated by Django 4.2.15 on 2024-08-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_subscribedusers_subscribeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeduser',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='email',
            field=models.CharField(help_text='Email address for newsletter signup', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
