# Generated by Django 4.2.15 on 2024-08-29 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_subscribeduser_id_alter_subscribeduser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapevent',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mapproject'),
        ),
    ]
