# Generated by Django 4.2.15 on 2024-08-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_mapevent_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapevent',
            name='map',
        ),
    ]
