# Generated by Django 4.2.15 on 2024-08-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_event_imgbackground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
