# Generated by Django 4.2.15 on 2024-08-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imgbackground',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
