# Generated by Django 4.2.15 on 2024-08-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_mapeventimage_description_mapeventimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeventimage',
            name='description',
            field=models.TextField(help_text='Enter an image description here'),
        ),
    ]
