# Generated by Django 4.2.15 on 2024-08-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_mapeventimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeventimage',
            name='title',
            field=models.CharField(help_text='Enter an image title here', max_length=200),
        ),
    ]
