# Generated by Django 4.2.15 on 2024-08-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_mapeventimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='head_image',
            field=models.ImageField(help_text='', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2019-03-25', help_text='Enter project start date'),
            preserve_default=False,
        ),
    ]
