# Generated by Django 4.2.15 on 2024-08-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_project_head_image_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='head_image',
            field=models.ImageField(help_text='', null=True, upload_to='images/'),
        ),
    ]
