# Generated by Django 4.2.15 on 2024-09-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_project_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapevent',
            name='link',
            field=models.CharField(blank=True, help_text='Enter an Event link here', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='head_image',
            field=models.ImageField(help_text='', null=True, upload_to='images/'),
        ),
    ]
