# Generated by Django 4.2.15 on 2024-09-09 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_mapevent_link_alter_project_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapevent',
            name='approved_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mapeventimage',
            name='mapevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mapevent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='head_image',
            field=models.ImageField(help_text='', null=True, upload_to='images/'),
        ),
    ]
