# Generated by Django 4.2.15 on 2024-09-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_mapevent_approved_by_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapevent',
            options={'ordering': ['date'], 'permissions': (('can_mark_approved', 'Set event as approved'),)},
        ),
        migrations.AlterField(
            model_name='project',
            name='head_image',
            field=models.ImageField(help_text='', null=True, upload_to='images/'),
        ),
    ]
