# Generated by Django 4.2.15 on 2024-09-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_project_head_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapevent',
            options={'get_latest_by': 'date', 'ordering': ['date'], 'permissions': (('can_mark_approved', 'Set event as approved'),)},
        ),
        migrations.AlterField(
            model_name='project',
            name='head_image',
            field=models.ImageField(help_text='', null=True, upload_to='images/'),
        ),
    ]
