# Generated by Django 5.0.9 on 2024-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_mapevent_options_alter_project_head_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapeventimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mapeventimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='project',
            name='head_image',
            field=models.ImageField(help_text='', null=True, upload_to='images/'),
        ),
    ]
