# Generated by Django 4.2.15 on 2024-09-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_project_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapevent',
            name='date',
            field=models.DateField(help_text="Enter the event's date"),
        ),
        migrations.AlterField(
            model_name='project',
            name='head_image',
            field=models.ImageField(help_text='', null=True, upload_to='images/'),
        ),
    ]
